-- MySQL Script generated by MySQL Workbench
-- mar 05 may 2020 16:58:39 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema loginUsuario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `loginUsuario` ;

-- -----------------------------------------------------
-- Schema loginUsuario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loginUsuario` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `loginUsuario` ;

-- -----------------------------------------------------
-- Table `loginUsuario`.`usuarioEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loginUsuario`.`usuarioEstudiante` (
  `idusuarioEstudiante` INT NOT NULL,
  `numUEstudianteBoleta` VARCHAR(45) NOT NULL,
  `nombreUEstudiante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numUEstudianteBoleta`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `numUEstudianteBoleta_UNIQUE` ON `loginUsuario`.`usuarioEstudiante` (`numUEstudianteBoleta` ASC);


-- -----------------------------------------------------
-- Table `loginUsuario`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loginUsuario`.`materias` (
  `idmaterias` INT NOT NULL,
  `NombreMateria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loginUsuario`.`materiasInscritas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loginUsuario`.`materiasInscritas` (
  `registro` INT NOT NULL AUTO_INCREMENT,
  `materiasInscritascol` VARCHAR(45) NOT NULL,
  `numUEstudianteBoleta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`registro`),
  CONSTRAINT `fk_materiasInscritas`
    FOREIGN KEY (`registro`)
    REFERENCES `loginUsuario`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_numUEstudianteBoleta_2`
    FOREIGN KEY (`numUEstudianteBoleta`)
    REFERENCES `loginUsuario`.`usuarioEstudiante` (`numUEstudianteBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `registro_UNIQUE` ON `loginUsuario`.`materiasInscritas` (`registro` ASC);

CREATE INDEX `fk_numUEstudianteBoleta_2_idx` ON `loginUsuario`.`materiasInscritas` (`numUEstudianteBoleta` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
